-- AGENT MEMORY SEED — generated by scripts/_seed-emit-sql.js
-- Embeddings NULL — backfill via /api/agent-memory-backfill-embeddings
-- Idempotent: skips rows where (tenant, role, title) already exists.

-- 1: atlas | ElevenLabs 429 -> use scribe_v1 STT, not OpenAI Whisper
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'ElevenLabs 429 -> use scribe_v1 STT, not OpenAI Whisper', 'When ElevenLabs returns 429 on TTS/chat, its STT (scribe_v1) sub-quota usually still has headroom. Keep using /api/jarvis-voice?op=stt (ElevenLabs scribe_v1). Do NOT fall back to OpenAI Whisper unless ElevenLabs is fully exhausted — it adds latency and a paid API touch with no upside on quota errors.',
       'api_gotcha', 'auto', '["elevenlabs","429","stt","voice"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'ElevenLabs 429 -> use scribe_v1 STT, not OpenAI Whisper');

-- 2: atlas | VAD silenceMs 600ms is the sweet spot post-streaming-TTS
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'VAD silenceMs 600ms is the sweet spot post-streaming-TTS', 'After shipping the streaming chat+TTS pipeline, 800ms VAD silence felt sluggish on the Jarvis PWA. Heath asked for snappier turn-take. 600ms cuts the gap noticeably without false-fire on natural pauses. 1500ms is too long. Below 500ms produces premature cutoffs.',
       'voice_ux', 'auto', '["vad","jarvis","voice","latency"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'VAD silenceMs 600ms is the sweet spot post-streaming-TTS');

-- 3: atlas | Conversation history MUST order DESC + LIMIT + reverse
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Conversation history MUST order DESC + LIMIT + reverse', 'When loading recent N messages from jarvis_messages, use order=created_at.desc + limit=N + slice().reverse() in JS. Loading ASC + LIMIT gives you the OLDEST N (every reply based on ancient context) instead of the most recent N. Heath called Jarvis a "conversational idiot" before this fix landed. See api/jarvis-voice.js handleChat() ~line 519.',
       'code_pattern', 'auto', '["supabase","pagination","jarvis","history"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Conversation history MUST order DESC + LIMIT + reverse');

-- 4: atlas | NEVER run vercel env pull or vercel link
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'NEVER run vercel env pull or vercel link', 'Both commands overwrite/destroy .env.local. Heath lost 60+ secrets on 2026-06-17 when an agent ran `vercel env pull`. Permanently banned. Use the Vercel dashboard for env management, or ask Heath for the specific var. Add a guard in any new automation that touches Vercel CLI.',
       'security', 'auto', '["vercel","secrets","banned-command"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'NEVER run vercel env pull or vercel link');

-- 5: atlas | Push-to-talk MUST release MediaStream tracks on conversation end
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Push-to-talk MUST release MediaStream tracks on conversation end', 'When stopping the Jarvis PWA push-to-talk, call stream.getTracks().forEach(t => t.stop()) AND null the MediaRecorder/AudioContext refs. Skipping this leaves the phone microphone LED on permanently (held by the page). Mobile Chrome especially never releases it on visibility change alone.',
       'code_pattern', 'auto', '["mediastream","mic","jarvis-pwa","mobile"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Push-to-talk MUST release MediaStream tracks on conversation end');

-- 6: atlas | Vite content-hashed bundle in-place edit MUST rename + update HTML
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Vite content-hashed bundle in-place edit MUST rename + update HTML', 'Editing a workspace-XXXX.js in place without renaming the file leaves the CDN serving the cached version forever (immutable headers). The deploy workflow is: build in ../Dossie -> cp dist/assets/workspace-*.js MeetDossie/assets/ -> update hash in BOTH app.html and workspace.html -> git rm the old bundle -> commit. All in one commit.',
       'workflow', 'auto', '["vite","vercel","cdn","deploy"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Vite content-hashed bundle in-place edit MUST rename + update HTML');

-- 7: atlas | Pre-push grep for merge conflict markers is mandatory
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Pre-push grep for merge conflict markers is mandatory', 'Before EVERY git push: run `git grep "<<<<<<<" -- "*.html" "*.js" "*.jsx" "*.json"`. Must return zero. Unresolved markers shipped to production at least three times across 2026-06. The grep takes 200ms; the prod-down incident takes hours.',
       'workflow', 'auto', '["git","merge","pre-push-gate"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Pre-push grep for merge conflict markers is mandatory');

-- 8: atlas | Mobile fixed overlay needs bottom:80+ AND z-index:110+
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Mobile fixed overlay needs bottom:80+ AND z-index:110+', 'The Dossie mobileTabBar is fixed bottom:0, height:60, zIndex:100. Any fixed overlay or floating button that needs to be visible above it must use bottom:>=80 AND zIndex:>=110. Lower z-index or smaller bottom value = invisible on mobile, perfect on desktop emulation. Bit me twice.',
       'code_pattern', 'auto', '["mobile","css","z-index","overlay"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Mobile fixed overlay needs bottom:80+ AND z-index:110+');

-- 9: atlas | Vercel CLI env adds are interactive — use the API instead
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Vercel CLI env adds are interactive — use the API instead', '`vercel env add` opens an interactive prompt that hangs headless agent runs. For server-to-server env updates, POST to https://api.vercel.com/v9/projects/{id}/env with the Vercel auth token. Same for `vercel env pull` — banned anyway, but the API would also be the right call.',
       'external_service_quirk', 'auto', '["vercel","cli","env"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Vercel CLI env adds are interactive — use the API instead');

-- 10: atlas | Supabase realtime publication: only adds, never auto-includes new tables
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'Supabase realtime publication: only adds, never auto-includes new tables', 'New tables do NOT automatically join the supabase_realtime publication. After every CREATE TABLE that the PWA needs to subscribe to, add: `alter publication supabase_realtime add table public.<name>`. Symptoms when missed: client.channel().on("postgres_changes",...) listener never fires; UI shows stale data until next poll.',
       'external_service_quirk', 'auto', '["supabase","realtime","publication"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'Supabase realtime publication: only adds, never auto-includes new tables');

-- 11: atlas | pgvector ivfflat with 100 lists is fine up to ~50k rows
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'pgvector ivfflat with 100 lists is fine up to ~50k rows', 'For agent_role_memory and similar small knowledge pools, ivfflat with lists=100 over a 1536-dim vector column gives sub-50ms nearest-neighbor search. Switch to hnsw or bump lists only if row count crosses ~50k OR query latency creeps over 200ms. Smaller datasets actually perform WORSE with more lists due to index sparsity.',
       'code_pattern', 'auto', '["pgvector","ivfflat","embeddings","supabase"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'pgvector ivfflat with 100 lists is fine up to ~50k rows');

-- 12: atlas | verifySupabaseToken throws — wrap caller in try/catch
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'atlas', 'verifySupabaseToken throws — wrap caller in try/catch', 'api/_middleware/auth.js verifySupabaseToken(req) throws AuthError with .status on bad/missing token. Every caller must try/catch and return res.status(err.status || 401). Letting it bubble causes a 500 the client cannot distinguish from a real server failure.',
       'code_pattern', 'auto', '["auth","supabase","middleware"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'atlas' AND m.title = 'verifySupabaseToken throws — wrap caller in try/catch');

-- 13: carter | Heath approves merges. Carter does NOT push to main.
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'carter', 'Heath approves merges. Carter does NOT push to main.', 'Locked 2026-06-18: Carter writes diffs and pushes to STAGING only. Atlas pulls, builds the bundle, runs Playwright APV against the staging URL, and merges to main only after APV passes. Carter shipping straight to main caused the prod-down incident + customer demo failure. No exceptions, no urgent patches.',
       'workflow', 'auto', '["process","merge","staging","carter"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'carter' AND m.title = 'Heath approves merges. Carter does NOT push to main.');

-- 14: carter | Founding price is $29/mo — NEVER change without explicit instruction
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'carter', 'Founding price is $29/mo — NEVER change without explicit instruction', 'CLAUDE.md Section 5 locks pricing. Founding Members = $29/mo, 50 spots, currently 12 taken. Solo monthly $79 / annual $39. Team $199. NEVER modify these values when refactoring pricing displays. If a refactor "simplifies" by removing the constant, add it back BEFORE the commit.',
       'heath_preference', 'auto', '["pricing","founding","locked"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'carter' AND m.title = 'Founding price is $29/mo — NEVER change without explicit instruction');

-- 15: carter | Dossie is always "she/her" — never "it" or "the app"
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'carter', 'Dossie is always "she/her" — never "it" or "the app"', 'Brand voice rule: in any user-facing copy (UI text, email body, tooltip, error message, marketing), Dossie is referred to as she/her, warm and feminine. "Dossie helps you" not "the app helps you" / "Dossie reminded me" not "the system reminded me". Tagline: Your deals. Her job.',
       'heath_preference', 'auto', '["brand","voice","copy"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'carter' AND m.title = 'Dossie is always "she/her" — never "it" or "the app"');

-- 16: carter | Test the customer flow signed-in, not as anonymous curl
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'carter', 'Test the customer flow signed-in, not as anonymous curl', 'For any customer-facing change, verification must use Playwright signed-in as heath.shepard@kw.com or demo@meetdossie.com and execute the exact action a customer would. Unauthenticated smoke tests (curl returning 401 against the API) do NOT count as verification. APV is the merge gate.',
       'workflow', 'auto', '["testing","apv","playwright"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'carter' AND m.title = 'Test the customer flow signed-in, not as anonymous curl');

-- 17: hadley | TREC 39-10 is Amendment to Contract, NOT Loan Assumption
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'hadley', 'TREC 39-10 is Amendment to Contract, NOT Loan Assumption', 'Common mix-up: form 39-10 (Amendment to Contract) vs. 41-3 (Loan Assumption Addendum). Always disambiguate by full form number AND title before generating prefill data. The TREC promulgated forms catalog is the source of truth — never infer form number from a colloquial name.',
       'legal_nuance', 'auto', '["trec","forms","amendment"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'hadley' AND m.title = 'TREC 39-10 is Amendment to Contract, NOT Loan Assumption');

-- 18: hadley | TREC 40-11: leaving interest-rate cap blank voids financing contingency
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'hadley', 'TREC 40-11: leaving interest-rate cap blank voids financing contingency', 'On TREC 40-11 (Third Party Financing Addendum), failing to fill the interest-rate cap field — or filling it with "market" — does NOT default to "any rate". It voids the financing contingency entirely under Texas case law. Always require a numeric cap. Flag any draft missing this as DEFECTIVE.',
       'legal_nuance', 'auto', '["trec","40-11","financing-contingency"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'hadley' AND m.title = 'TREC 40-11: leaving interest-rate cap blank voids financing contingency');

-- 19: hadley | DocuSeal template 4018208 has duplicate "Seller 2" field — re-map carefully
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'hadley', 'DocuSeal template 4018208 has duplicate "Seller 2" field — re-map carefully', 'When prefilling via DocuSeal API for the TREC resale contract template 4018208, the field set includes two distinct "Seller 2" entries (one signature, one printed name). Match by full slug, not display name. Mis-mapping caused contract draft failures noted in 2026-06-17 session handoff.',
       'external_service_quirk', 'auto', '["docuseal","trec","4018208","prefill"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'hadley' AND m.title = 'DocuSeal template 4018208 has duplicate "Seller 2" field — re-map carefully');

-- 20: hadley | Full transaction template must work before any TREC fill goes live
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'hadley', 'Full transaction template must work before any TREC fill goes live', 'Per-form ship is forbidden. Buyer-side package = TREC 20-17 + 40-11 + conditional addendums ALL must fill correctly before any TREC fill is enabled in customer UI. Partial functionality misleads agents into legally defective drafts. Locked 2026-06-17.',
       'legal_nuance', 'auto', '["trec","fill-form","ship-gate"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'hadley' AND m.title = 'Full transaction template must work before any TREC fill goes live');

-- 21: hadley | DocuSeal is the default e-sign; DocuSign is the paid upgrade
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'hadley', 'DocuSeal is the default e-sign; DocuSign is the paid upgrade', 'Texas ESIGN/UETA renders DocuSeal-signed documents enforceable in real estate. Default Dossie deals use DocuSeal. DocuSign stays an opt-in upgrade for customers who want brand recognition or whose brokerage compliance requires it. No build of the DocuSign integration until 30+ paying customers exist. Locked 2026-06-19.',
       'legal_nuance', 'auto', '["docuseal","docusign","esign","compliance"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'hadley' AND m.title = 'DocuSeal is the default e-sign; DocuSign is the paid upgrade');

-- 22: jarvis | Heath addresses preference = "sir" (varies like a real EA)
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Heath addresses preference = "sir" (varies like a real EA)', 'Heath''s tenants.addressing_pref is "sir". Use it naturally but VARY phrasing like a real executive assistant: "sir", "Heath", a question without an address. Never robotic. Never "Mr. Shepard" (too formal). Never "boss" (off-brand). Default to sir, but if the last 3 replies all started with sir, drop it on the 4th.',
       'heath_preference', 'auto', '["addressing","persona","voice"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Heath addresses preference = "sir" (varies like a real EA)');

-- 23: jarvis | Heath prefers Iron Man HUD aesthetic — electric cyan, info-dense, always moving
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Heath prefers Iron Man HUD aesthetic — electric cyan, info-dense, always moving', 'V5 HUD spec: Earth wireframe + city lights + hex-grid background + electric cyan accents + glassmorphic panels + seamless rotation + always-moving (no static states). Carter re-reads reference_jarvis_v5_visual_spec.md every round. Static UI = wrong. Stop-and-go animations = wrong.',
       'heath_preference', 'auto', '["hud","jarvis-pwa","aesthetic"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Heath prefers Iron Man HUD aesthetic — electric cyan, info-dense, always moving');

-- 24: jarvis | Default reply = 1-2 sentences. No bullet list. No threads register.
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Default reply = 1-2 sentences. No bullet list. No threads register.', 'Heath set radical brevity 2026-06-18. Even "tight" replies were too long. Default = max 2 sentences. No "here''s the plan" preamble. No multi-paragraph diagnoses. The Open Threads register is OFF unless asked. HUD card is the durable view; chat is fleeting status. Expand only on explicit Heath request.',
       'heath_preference', 'auto', '["brevity","tone","voice"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Default reply = 1-2 sentences. No bullet list. No threads register.');

-- 25: jarvis | NEVER curl Telegram getUpdates — steals poll lock from the plugin
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'NEVER curl Telegram getUpdates — steals poll lock from the plugin', 'The telegram MCP plugin holds a long-poll lock against the bot getUpdates endpoint. Any concurrent curl to /getUpdates causes the plugin to drop inbound messages silently. Symptom: "Telegram MCP inbound dropped" notes in session handoffs. NEVER hit Telegram API directly from a tool that runs alongside the plugin.',
       'api_gotcha', 'auto', '["telegram","mcp","getupdates","banned"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'NEVER curl Telegram getUpdates — steals poll lock from the plugin');

-- 26: jarvis | Carter "done" is NOT actionable — only Atlas APV PASS triggers merge proposal
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Carter "done" is NOT actionable — only Atlas APV PASS triggers merge proposal', 'Pattern: Carter reports "ready for merge" -> actually broken. Locked: Jarvis never asks Heath to merge based on Carter''s word. Carter ships to staging -> Jarvis auto-spawns Atlas APV -> only Atlas-confirmed PASS pings Heath. Saves 5+ false-positive merge requests per day.',
       'workflow', 'auto', '["process","apv","merge-gate"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Carter "done" is NOT actionable — only Atlas APV PASS triggers merge proposal');

-- 27: jarvis | Customer bugs preempt other work + email customer back personally
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Customer bugs preempt other work + email customer back personally', 'Any founding-member bug report jumps to the top of the queue. Verify on staging by eye, get Heath''s merge approval, ship, THEN email the customer thanking them + giving refresh/clear-cache instructions. Brittney pattern 2026-06-17. Tone: calm friend, small stakes. Never quantify breadth ("hit every customer"). Never name vendors as cause (Vercel/Supabase/Resend).',
       'customer_pattern', 'auto', '["customer-support","brittney","tone"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Customer bugs preempt other work + email customer back personally');

-- 28: jarvis | Heath = 100% SC disabled veteran — qualifies for SDVOSB
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'jarvis', 'Heath = 100% SC disabled veteran — qualifies for SDVOSB', 'Heath is a 100% service-connected disabled veteran. Eligible for SDVOSB certification, TX franchise tax exemption, SBA Express loans, AWS/Azure veteran programs, GitHub for Veterans. Surface these whenever a relevant cost/grant/cert decision comes up. Apply at SDVOSB cert when forming Dossie LLC.',
       'heath_preference', 'auto', '["veteran","sdvosb","grants"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'jarvis' AND m.title = 'Heath = 100% SC disabled veteran — qualifies for SDVOSB');

-- 29: pierce | Founder outreach = warm friendly, never confrontational
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'pierce', 'Founder outreach = warm friendly, never confrontational', 'Outreach to dormant founding members: open with a warm 1-line opener (NOT "Name, Heath."). Frame founders as having a direct line to the builder, eager to hear feedback + make it work. No transactional tone. No "we noticed you haven''t logged in" guilt trip. Locked 2026-06-17 after Pierce reactivation rewrite.',
       'customer_pattern', 'auto', '["outreach","tone","founder"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'pierce' AND m.title = 'Founder outreach = warm friendly, never confrontational');

-- 30: pierce | Subscriber emails: Tue-Thu 8:30am CST ONLY
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'pierce', 'Subscriber emails: Tue-Thu 8:30am CST ONLY', 'Never schedule mass subscriber emails Mon, Fri, evenings, or weekends. Open rates drop 30-40% outside the Tue/Wed/Thu 8:30am CST window. The "Weekly Update" goes Friday only as exception because it''s explicitly weekly-themed; even then send no later than 9am.',
       'workflow', 'auto', '["email","send-window","open-rate"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'pierce' AND m.title = 'Subscriber emails: Tue-Thu 8:30am CST ONLY');

-- 31: pierce | Persona Dossie-usage timeframes = "recently" / "last few weeks"
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'pierce', 'Persona Dossie-usage timeframes = "recently" / "last few weeks"', 'When writing persona-driven marketing copy (Brenda, Patricia, Victor), NEVER imply multi-month or multi-year Dossie use. Product is ~6 weeks old. Use "recently", "over the last few weeks", "since I started using Dossie". Multi-month claims look fabricated to anyone who knows the launch date.',
       'customer_pattern', 'auto', '["persona","marketing","copy","truth"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'pierce' AND m.title = 'Persona Dossie-usage timeframes = "recently" / "last few weeks"');

-- 32: sage | Reels pipeline = Kling + ElevenLabs + ffmpeg + Submagic — NOT Creatomate
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'sage', 'Reels pipeline = Kling + ElevenLabs + ffmpeg + Submagic — NOT Creatomate', 'Dossie reel workflow: Kling AI clips in Media/Videos/ -> ElevenLabs Charlie voiceover -> ffmpeg concat/freeze -> Supabase upload (auth token only, NO apikey header) -> Submagic Hormozi 1 captions. Creatomate is for the lifestyle-video pipeline, not reels. Mixing the two has corrupted output twice.',
       'workflow', 'auto', '["reels","kling","submagic","video"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'sage' AND m.title = 'Reels pipeline = Kling + ElevenLabs + ffmpeg + Submagic — NOT Creatomate');

-- 33: sage | NEVER fabricate specifics in customer-facing posts
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'sage', 'NEVER fabricate specifics in customer-facing posts', 'Social posts, emails, marketing copy must only reference VERIFIED facts. No invented member numbers, fake timestamps, hallucinated features, or debug stories that did not happen. If a number isn''t in the DB or CLAUDE.md, do not include it. Locked rule.',
       'workflow', 'auto', '["brand","truth","social"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'sage' AND m.title = 'NEVER fabricate specifics in customer-facing posts');

-- 34: sage | Founding Files FB group autoposts via fb-group-poster.js
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'sage', 'Founding Files FB group autoposts via fb-group-poster.js', 'Private group facebook.com/share/g/1P2QL9T42t/ — DossieBot Chrome profile is logged in. To post: insert row into group_posts (group_name, group_url, post_body, status="approved", template_id="direct"), then run `node scripts/fb-group-poster.js --post-id <uuid>`. CLOSE the DossieBot Chrome window first or Playwright will collide with the profile lock.',
       'workflow', 'auto', '["founding-files","facebook","autopost"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'sage' AND m.title = 'Founding Files FB group autoposts via fb-group-poster.js');

-- 35: quinn | After every Carter staging push, run full test suite — no "non-blocking" skips
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'quinn', 'After every Carter staging push, run full test suite — no "non-blocking" skips', 'Quinn auto-spawns after every Carter staging push. Loop with Carter up to 3 rounds to fix ALL failures, including "non-blocking" ones. Heath says "merge it" before Cole touches main — no exceptions. Cole never auto-merges. Heath is always the final gate.',
       'workflow', 'auto', '["qa","staging","merge-gate"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'quinn' AND m.title = 'After every Carter staging push, run full test suite — no "non-blocking" skips');

-- 36: quinn | Mobile bug diagnostic = on-page overlay activated by URL flag
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'quinn', 'Mobile bug diagnostic = on-page overlay activated by URL flag', 'When a UI bug breaks on Heath''s real mobile but Playwright emulation says clean, STOP guessing after attempt 2. Build a visible on-page event-stream overlay activated by a URL flag (?debug=1). Heath taps the broken flow, screenshots the log, you diagnose in one round-trip. Proven 2026-05-24 mobile-scan bug.',
       'workflow', 'auto', '["debug","mobile","overlay"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'quinn' AND m.title = 'Mobile bug diagnostic = on-page overlay activated by URL flag');

-- 37: sterling | Sterling never PREDICTS — surfaces info and risk-managed orders
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'sterling', 'Sterling never PREDICTS — surfaces info and risk-managed orders', 'Sterling is honest about market unpredictability. Job is to surface catalysts, news, risk factors, and draft RISK-MANAGED order ideas. Never "buy this stock", never confident price predictions. Always include a stop-loss + position-sizing rule with every order draft. Educate, don''t hype.',
       'heath_preference', 'auto', '["markets","risk","tone"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'sterling' AND m.title = 'Sterling never PREDICTS — surfaces info and risk-managed orders');

-- 38: ridge | Vercel cron "configured" != "firing" — check last invocation timestamp
INSERT INTO public.agent_role_memory (tenant_id, agent_role, title, content, category, validation_status, tags, usage_count)
SELECT t.id, 'ridge', 'Vercel cron "configured" != "firing" — check last invocation timestamp', 'A vercel.json cron entry is a SCHEDULE, not a proof of execution. To verify a cron is alive, pull the last invocation timestamp via the Vercel deployments + runtime logs (or write a "cron heartbeat" row into a table and check freshness). If no fire in the expected window, flag as DEAD CRON. Locked under Atlas A2 rule, applies to Ridge SRE checks.',
       'workflow', 'auto', '["cron","vercel","observability"]'::jsonb, 0
FROM public.tenants t
WHERE t.slug = 'heath'
  AND NOT EXISTS (SELECT 1 FROM public.agent_role_memory m WHERE m.tenant_id = t.id AND m.agent_role = 'ridge' AND m.title = 'Vercel cron "configured" != "firing" — check last invocation timestamp');
