# scripts/install-mission-watchdog-task.ps1
#
# SV-ENG-WATCHDOG-003 (Atlas, 2026-06-11)
#
# Registers "Dossie Mission Watchdog" in Windows Task Scheduler.
# This is the PRIMARY trigger for the Mission Watchdog (cron-job.org is
# explicitly NOT used because today's failure was specifically because the
# veto-mode cron was code-only and never registered anywhere -- we're not
# going to repeat that mistake on the watchdog itself).
#
# Cadence: every hour 8 AM - 8 PM CDT (13 trigger times: 8, 9, 10, ..., 20).
# Action:  curl with Bearer ${CRON_SECRET} to https://meetdossie.com/api/cron-mission-watchdog
#
# Run this script as Administrator the first time. It is idempotent --
# re-running unregisters and re-registers.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/install-mission-watchdog-task.ps1
#
# Verify after install:
#   schtasks /Query /TN "Dossie Mission Watchdog" /V /FO LIST
#   Get-ScheduledTaskInfo -TaskName "Dossie Mission Watchdog"

$ErrorActionPreference = 'Stop'

$TaskName    = 'Dossie Mission Watchdog'
$Description = 'Hourly 8am-8pm CDT: pings api/cron-mission-watchdog to route around any platform falling behind its posting pace.'
$EnvPath     = Join-Path $PSScriptRoot '..' '.env.local'

# ---- Read CRON_SECRET from .env.local ---------------------------------------
if (!(Test-Path $EnvPath)) {
    Write-Host "FATAL: $EnvPath not found. Cannot read CRON_SECRET." -ForegroundColor Red
    exit 1
}
$cronSecret = $null
Get-Content $EnvPath | ForEach-Object {
    if ($_ -match '^\s*CRON_SECRET\s*=\s*"?([^"\r\n]+)"?\s*$') {
        $cronSecret = $Matches[1]
    }
}
if (-not $cronSecret) {
    Write-Host "FATAL: CRON_SECRET not found in $EnvPath" -ForegroundColor Red
    exit 1
}

# ---- Build the curl command -------------------------------------------------
# Use curl.exe (Windows 10+ has it pre-installed at C:\Windows\System32\curl.exe).
# We intentionally do NOT use Invoke-WebRequest because Task Scheduler running
# PowerShell with -NonInteractive sometimes fights TLS handshakes on older PS5.
$curlPath = 'C:\Windows\System32\curl.exe'
$url      = 'https://meetdossie.com/api/cron-mission-watchdog'
$args     = "-fsS -H ""Authorization: Bearer $cronSecret"" $url"

# Log to scripts/atlas-runs/mission-watchdog-YYYY-MM-DD.log (one per day)
$logDir = Join-Path $PSScriptRoot 'atlas-runs'
if (!(Test-Path $logDir)) { New-Item -ItemType Directory -Force -Path $logDir | Out-Null }

# Wrap the call so the output lands in today's log file.
$wrappedCommand = "& '$curlPath' $args >> '$logDir\mission-watchdog-' + (Get-Date -Format yyyy-MM-dd) + '.log' 2>&1"
# Persist the wrapper as a one-off PS1 we invoke from the task action.
$runnerPath = Join-Path $PSScriptRoot 'mission-watchdog-runner.ps1'
@"
# Auto-generated by install-mission-watchdog-task.ps1 -- do not edit by hand.
`$ts = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'
`$logPath = Join-Path '$logDir' ('mission-watchdog-' + (Get-Date -Format yyyy-MM-dd) + '.log')
Add-Content -Path `$logPath -Value "[`$ts] start"
try {
    `$response = & '$curlPath' -fsS -H 'Authorization: Bearer $cronSecret' '$url' 2>&1
    Add-Content -Path `$logPath -Value "[`$ts] response: `$response"
} catch {
    Add-Content -Path `$logPath -Value "[`$ts] ERROR: `$(`$_.Exception.Message)"
}
Add-Content -Path `$logPath -Value "[`$ts] end"
"@ | Set-Content -Path $runnerPath -Encoding ASCII

# ---- Tear down any existing task -------------------------------------------
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Removing existing scheduled task '$TaskName'..."
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# ---- Register the task ------------------------------------------------------
# Triggers: hourly from 13:00 UTC (8 AM CDT) through 01:00 UTC the next day.
# Windows Task Scheduler runs in LOCAL time -- since Heath's machine is in
# America/Chicago, we use 08:00-20:00 local. If he moves machines / timezones
# we'd need to re-register; the Vercel cron is the belt-and-suspenders.
$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$runnerPath`""

# 13 hourly triggers 08:00, 09:00, ..., 20:00 local.
$triggers = @()
for ($h = 8; $h -le 20; $h++) {
    $time = (Get-Date).Date.AddHours($h)
    $triggers += New-ScheduledTaskTrigger -Daily -At $time
}

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType S4U -RunLevel Highest

Register-ScheduledTask `
    -TaskName $TaskName `
    -Description $Description `
    -Action $action `
    -Trigger $triggers `
    -Settings $settings `
    -Principal $principal | Out-Null

Write-Host "OK -- '$TaskName' registered with $($triggers.Count) hourly triggers 08:00-20:00 local." -ForegroundColor Green
Write-Host "Runner: $runnerPath" -ForegroundColor Gray
Write-Host "Log:    $logDir\mission-watchdog-YYYY-MM-DD.log" -ForegroundColor Gray
Write-Host ""
Write-Host "Verify: schtasks /Query /TN ""$TaskName"" /V /FO LIST" -ForegroundColor Yellow
Write-Host "Test now: Start-ScheduledTask -TaskName ""$TaskName""" -ForegroundColor Yellow
