# Auto-generated by install-mission-watchdog-task.ps1 -- do not edit by hand.
# NOTE: This script reads CRON_SECRET from environment. Set via Windows Task Scheduler or manually before running.

$ts = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'
$logPath = Join-Path 'C:\Users\Heath Shepard\Desktop\MeetDossie\scripts\atlas-runs' ('mission-watchdog-' + (Get-Date -Format yyyy-MM-dd) + '.log')
Add-Content -Path $logPath -Value "[$ts] start"

$cronSecret = $env:CRON_SECRET
if (-not $cronSecret) {
  Add-Content -Path $logPath -Value "[$ts] ERROR: CRON_SECRET env var not set"
  exit 1
}

try {
    $response = & 'C:\Windows\System32\curl.exe' -fsS -H "Authorization: Bearer $cronSecret" 'https://meetdossie.com/api/cron-mission-watchdog' 2>&1
    Add-Content -Path $logPath -Value "[$ts] response: $response"
} catch {
    Add-Content -Path $logPath -Value "[$ts] ERROR: $($_.Exception.Message)"
}
Add-Content -Path $logPath -Value "[$ts] end"
