"""Vercel Serverless Function: /api/render-card

Renders a branded Dossie social card (Instagram 1080×1080 or Facebook 1200×630)
and uploads it to Supabase Storage `social-cards` bucket. Returns the public URL.

Called by cron-generate-posts.js for each Instagram/Facebook row generated by
the daily content cron. The URL goes into social_posts.media_url so
cron-publish-approved.js attaches it as mediaItems[0] when posting to Zernio.

Auth: Authorization: Bearer ${CRON_SECRET}
Method: POST
Body: {
  "platform": "instagram" | "facebook",
  "hook":     "<headline>",
  "content":  "<body copy, may contain real \\n>",
  "persona":  "brenda" | "patricia" | "victor" | null,
  "post_id":  "<deterministic id used as the storage filename>"
}
Response: { "ok": true, "publicUrl": "https://...supabase.co/.../public/social-cards/{post_id}.png" }

The renderer logic mirrors scripts/render-social-card.py — keep them in sync
for the brand to stay coherent across CLI testing and the daily cron.
"""
import base64
import io
import json
import os
import sys
import urllib.parse
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ─── Brand palette (matches Dossie web app) ──────────────────────────────
SALMON           = (232, 146, 124)
CREAM            = (253, 252, 250)
BEIGE            = (240, 235, 227)
WARM_GRAY_LIGHT  = (163, 158, 148)
WARM_GRAY_DARK   = (122, 116, 104)
INK              = (38, 32, 24)

# ─── Asset paths (Vercel includes Media/_fonts + Media/dossie-logo-d.png) ─
# __file__ is /var/task/api/render-card.py on Vercel; .parent.parent is
# the deployment root (/var/task).
ROOT = Path(__file__).resolve().parent.parent
FONT_BOLD          = ROOT / "Media" / "_fonts" / "CormorantGaramond-Bold.ttf"
FONT_SEMIBOLD      = ROOT / "Media" / "_fonts" / "CormorantGaramond-SemiBold.ttf"
LOGO_D             = ROOT / "Media" / "dossie-logo-d.png"

# Linux fallback fonts on Vercel's Amazon Linux runtime.
FONT_FALLBACK_BOLD    = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FONT_FALLBACK_REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

PLATFORM_DIMS = {
    "instagram": (1080, 1080),
    "facebook":  (1200, 630),
}

PERSONA_DISPLAY = {
    "brenda":   "— Brenda Martinez · San Antonio REALTOR",
    "patricia": "— Patricia Morrison · Dossie founder",
    "victor":   "— Victor Hayes · Houston REALTOR",
}

SUPABASE_URL              = os.environ.get("SUPABASE_URL", "")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
CRON_SECRET               = os.environ.get("CRON_SECRET", "")
STORAGE_BUCKET            = "social-cards"


# ─── Rendering primitives ────────────────────────────────────────────────

def load_font(path, size: int):
    try:
        return ImageFont.truetype(str(path), size=size)
    except (OSError, IOError):
        fb = FONT_FALLBACK_BOLD if "Bold" in str(path) else FONT_FALLBACK_REGULAR
        try:
            return ImageFont.truetype(fb, size=size)
        except (OSError, IOError):
            return ImageFont.load_default()


def text_size(draw, text, font):
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


def wrap_to_width(draw, text, font, max_width):
    out = []
    for paragraph in text.split("\n"):
        if not paragraph.strip():
            out.append("")
            continue
        words = paragraph.split()
        line = ""
        for w in words:
            cand = (line + " " + w).strip()
            if text_size(draw, cand, font)[0] <= max_width:
                line = cand
            else:
                if line:
                    out.append(line)
                line = w
        if line:
            out.append(line)
    return out


def fit_font_size(draw, text, font_path, max_width, max_height,
                  start, min_size=24, line_spacing=1.2):
    lo, hi = min_size, start
    best = (load_font(font_path, min_size), [], 0)
    while lo <= hi:
        mid = (lo + hi) // 2
        f = load_font(font_path, mid)
        lines = wrap_to_width(draw, text, f, max_width)
        line_h = text_size(draw, "Hg", f)[1]
        total_h = int(len(lines) * line_h * line_spacing)
        if total_h <= max_height and all(text_size(draw, ln, f)[0] <= max_width for ln in lines if ln):
            best = (f, lines, total_h)
            lo = mid + 1
        else:
            hi = mid - 1
    return best


def draw_lines(draw, lines, font, x, y, color, line_spacing=1.2):
    line_h = text_size(draw, "Hg", font)[1]
    step = int(line_h * line_spacing)
    for ln in lines:
        if ln:
            draw.text((x, y), ln, font=font, fill=color)
        y += step
    return y


def render_card_png(platform, hook, content, persona):
    """Render the card and return PNG bytes."""
    if platform not in PLATFORM_DIMS:
        raise ValueError(f"unsupported platform '{platform}'")
    W, H = PLATFORM_DIMS[platform]

    canvas = Image.new("RGB", (W, H), CREAM)
    draw = ImageDraw.Draw(canvas)

    stripe_h = int(H * 0.025)
    draw.rectangle([(0, 0), (W, stripe_h)], fill=SALMON)

    margin = int(W * 0.07)
    footer_h = int(H * (0.18 if platform == "instagram" else 0.22))
    footer_top = H - footer_h
    draw.line([(margin, footer_top), (W - margin, footer_top)], fill=BEIGE, width=2)

    content_top = stripe_h + int(H * 0.06)
    content_bottom = footer_top - int(H * 0.04)
    content_w = W - 2 * margin
    content_h = content_bottom - content_top

    if hook:
        hook_max_h = int(content_h * 0.45)
        hook_start = int(H * 0.10) if platform == "instagram" else int(H * 0.12)
        hook_font, hook_lines, _ = fit_font_size(
            draw, hook, FONT_BOLD, content_w, hook_max_h, hook_start, min_size=36
        )
        y = draw_lines(draw, hook_lines, hook_font, margin, content_top, INK, line_spacing=1.1)
        body_top = y + int(H * 0.025)
    else:
        body_top = content_top

    body_max_h = max(content_bottom - body_top, int(H * 0.1))
    body_start = int(H * 0.045) if platform == "instagram" else int(H * 0.055)
    body_font, body_lines, _ = fit_font_size(
        draw, content, FONT_SEMIBOLD, content_w, body_max_h, body_start, min_size=22
    )
    draw_lines(draw, body_lines, body_font, margin, body_top, WARM_GRAY_DARK, line_spacing=1.3)

    # Footer row 1: D logo + Dossie wordmark on left, URL on right
    has_signature = bool(persona) and persona in PERSONA_DISPLAY
    row1_y_center = footer_top + int(footer_h * (0.38 if has_signature else 0.5))

    logo_target_h = int(footer_h * 0.45)
    if LOGO_D.exists():
        logo = Image.open(LOGO_D).convert("RGBA")
        ratio = logo_target_h / logo.height
        logo_w = int(logo.width * ratio)
        logo = logo.resize((logo_w, logo_target_h), Image.LANCZOS)
        canvas.paste(logo, (margin, row1_y_center - logo_target_h // 2), logo)
        wordmark_left = margin + logo_w + int(W * 0.022)
    else:
        wordmark_left = margin

    wm_font = load_font(FONT_BOLD, int(footer_h * 0.30))
    wm_w, wm_h = text_size(draw, "Dossie", wm_font)
    draw.text((wordmark_left, row1_y_center - wm_h // 2), "Dossie", font=wm_font, fill=INK)

    url_font = load_font(FONT_FALLBACK_BOLD, int(footer_h * 0.20))
    url_text = "meetdossie.com/founding"
    url_w, url_h = text_size(draw, url_text, url_font)
    url_x = W - margin - url_w
    url_y = (row1_y_center - wm_h // 2) + (wm_h - url_h)
    draw.text((url_x, url_y), url_text, font=url_font, fill=SALMON)

    if has_signature:
        row2_y_center = footer_top + int(footer_h * 0.78)
        sig_size = int(footer_h * 0.16)
        sig_font = load_font(FONT_FALLBACK_REGULAR, sig_size)
        sig_text = PERSONA_DISPLAY[persona]
        sig_w, sig_h = text_size(draw, sig_text, sig_font)
        max_sig_w = W - 2 * margin
        while sig_w > max_sig_w and sig_size > 14:
            sig_size -= 2
            sig_font = load_font(FONT_FALLBACK_REGULAR, sig_size)
            sig_w, sig_h = text_size(draw, sig_text, sig_font)
        draw.text((W - margin - sig_w, row2_y_center - sig_h // 2),
                  sig_text, font=sig_font, fill=WARM_GRAY_LIGHT)

    buf = io.BytesIO()
    canvas.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


# ─── Supabase Storage upload ─────────────────────────────────────────────

def upload_to_storage(png_bytes, object_path):
    """PUT the PNG to Storage with upsert. Returns the public URL on success.

    Uses x-upsert: true so re-renders of the same post_id overwrite cleanly.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        raise RuntimeError("SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not configured")
    object_path = urllib.parse.quote(object_path, safe="/")
    upload_url = f"{SUPABASE_URL}/storage/v1/object/{STORAGE_BUCKET}/{object_path}"
    req = urllib.request.Request(
        upload_url,
        data=png_bytes,
        headers={
            "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
            "Content-Type": "image/png",
            "x-upsert": "true",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            if r.status not in (200, 201):
                raise RuntimeError(f"Storage upload returned {r.status}")
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "replace") if e.fp else ""
        raise RuntimeError(f"Storage upload HTTP {e.code}: {body[:300]}") from e
    return f"{SUPABASE_URL}/storage/v1/object/public/{STORAGE_BUCKET}/{object_path}"


# ─── Vercel handler ──────────────────────────────────────────────────────

from http.server import BaseHTTPRequestHandler


class handler(BaseHTTPRequestHandler):
    def _send_json(self, status, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        # Auth
        auth = self.headers.get("Authorization", "") or self.headers.get("authorization", "")
        if not CRON_SECRET or auth != f"Bearer {CRON_SECRET}":
            return self._send_json(401, {"ok": False, "error": "Unauthorized"})

        # Parse body
        try:
            length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(length).decode("utf-8") if length > 0 else ""
            body = json.loads(raw) if raw else {}
        except Exception as e:
            return self._send_json(400, {"ok": False, "error": f"bad JSON body: {e}"})

        platform = (body.get("platform") or "").lower()
        hook     = body.get("hook") or ""
        content  = body.get("content") or ""
        persona  = (body.get("persona") or "").lower() or None
        post_id  = body.get("post_id") or ""

        if platform not in PLATFORM_DIMS:
            return self._send_json(400, {"ok": False, "error": f"platform must be instagram or facebook, got '{platform}'"})
        if not content and not hook:
            return self._send_json(400, {"ok": False, "error": "content or hook required"})
        if not post_id:
            return self._send_json(400, {"ok": False, "error": "post_id required (used as storage filename)"})

        # Sanitize post_id for use as object path.
        safe_id = "".join(c if c.isalnum() or c in "-_" else "-" for c in post_id)[:120]
        object_path = f"{platform}/{safe_id}.png"

        try:
            png_bytes = render_card_png(platform, hook, content, persona)
            public_url = upload_to_storage(png_bytes, object_path)
        except Exception as e:
            return self._send_json(500, {"ok": False, "error": f"render or upload failed: {e}"})

        return self._send_json(200, {
            "ok": True,
            "publicUrl": public_url,
            "platform": platform,
            "size_bytes": len(png_bytes),
            "storage_path": object_path,
        })

    def do_GET(self):
        return self._send_json(200, {"ok": True, "service": "render-card",
                                     "platforms": list(PLATFORM_DIMS.keys())})
